//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/api/networking/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotationPromptParams) DeepCopyInto(out *AnnotationPromptParams) {
	*out = *in
	if in.EnableAnnotations != nil {
		in, out := &in.EnableAnnotations, &out.EnableAnnotations
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotationPromptParams.
func (in *AnnotationPromptParams) DeepCopy() *AnnotationPromptParams {
	if in == nil {
		return nil
	}
	out := new(AnnotationPromptParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.TargetMemoryUtilizationPercentage != nil {
		in, out := &in.TargetMemoryUtilizationPercentage, &out.TargetMemoryUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingSpec.
func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureProvider) DeepCopyInto(out *AzureProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
	out.APIKey = in.APIKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureProvider.
func (in *AzureProvider) DeepCopy() *AzureProvider {
	if in == nil {
		return nil
	}
	out := new(AzureProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchesInlineProviders) DeepCopyInto(out *BatchesInlineProviders) {
	*out = *in
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(InlineReferenceProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchesInlineProviders.
func (in *BatchesInlineProviders) DeepCopy() *BatchesInlineProviders {
	if in == nil {
		return nil
	}
	out := new(BatchesInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchesProvidersSpec) DeepCopyInto(out *BatchesProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(BatchesRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(BatchesInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchesProvidersSpec.
func (in *BatchesProvidersSpec) DeepCopy() *BatchesProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(BatchesProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchesRemoteProviders) DeepCopyInto(out *BatchesRemoteProviders) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchesRemoteProviders.
func (in *BatchesRemoteProviders) DeepCopy() *BatchesRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(BatchesRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BedrockProvider) DeepCopyInto(out *BedrockProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AWSAccessKeyID != nil {
		in, out := &in.AWSAccessKeyID, &out.AWSAccessKeyID
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AWSSecretAccessKey != nil {
		in, out := &in.AWSSecretAccessKey, &out.AWSSecretAccessKey
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AWSSessionToken != nil {
		in, out := &in.AWSSessionToken, &out.AWSSessionToken
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.TotalMaxAttempts != nil {
		in, out := &in.TotalMaxAttempts, &out.TotalMaxAttempts
		*out = new(int)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(int)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(int)
		**out = **in
	}
	if in.SessionTTL != nil {
		in, out := &in.SessionTTL, &out.SessionTTL
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BedrockProvider.
func (in *BedrockProvider) DeepCopy() *BedrockProvider {
	if in == nil {
		return nil
	}
	out := new(BedrockProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BraveSearchProvider) DeepCopyInto(out *BraveSearchProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	out.APIKey = in.APIKey
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BraveSearchProvider.
func (in *BraveSearchProvider) DeepCopy() *BraveSearchProvider {
	if in == nil {
		return nil
	}
	out := new(BraveSearchProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChunkRetrievalParams) DeepCopyInto(out *ChunkRetrievalParams) {
	*out = *in
	if in.ChunkMultiplier != nil {
		in, out := &in.ChunkMultiplier, &out.ChunkMultiplier
		*out = new(int)
		**out = **in
	}
	if in.MaxTokensInContext != nil {
		in, out := &in.MaxTokensInContext, &out.MaxTokensInContext
		*out = new(int)
		**out = **in
	}
	if in.DefaultRerankerStrategy != nil {
		in, out := &in.DefaultRerankerStrategy, &out.DefaultRerankerStrategy
		*out = new(string)
		**out = **in
	}
	if in.RRFImpactFactor != nil {
		in, out := &in.RRFImpactFactor, &out.RRFImpactFactor
		*out = new(string)
		**out = **in
	}
	if in.WeightedSearchAlpha != nil {
		in, out := &in.WeightedSearchAlpha, &out.WeightedSearchAlpha
		*out = new(string)
		**out = **in
	}
	if in.DefaultSearchMode != nil {
		in, out := &in.DefaultSearchMode, &out.DefaultSearchMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChunkRetrievalParams.
func (in *ChunkRetrievalParams) DeepCopy() *ChunkRetrievalParams {
	if in == nil {
		return nil
	}
	out := new(ChunkRetrievalParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompactionConfig) DeepCopyInto(out *CompactionConfig) {
	*out = *in
	if in.DefaultCompactThreshold != nil {
		in, out := &in.DefaultCompactThreshold, &out.DefaultCompactThreshold
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompactionConfig.
func (in *CompactionConfig) DeepCopy() *CompactionConfig {
	if in == nil {
		return nil
	}
	out := new(CompactionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigGenerationStatus) DeepCopyInto(out *ConfigGenerationStatus) {
	*out = *in
	in.GeneratedAt.DeepCopyInto(&out.GeneratedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigGenerationStatus.
func (in *ConfigGenerationStatus) DeepCopy() *ConfigGenerationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigGenerationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeyRef) DeepCopyInto(out *ConfigMapKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeyRef.
func (in *ConfigMapKeyRef) DeepCopy() *ConfigMapKeyRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextPromptParams) DeepCopyInto(out *ContextPromptParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextPromptParams.
func (in *ContextPromptParams) DeepCopy() *ContextPromptParams {
	if in == nil {
		return nil
	}
	out := new(ContextPromptParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContextualRetrievalParams) DeepCopyInto(out *ContextualRetrievalParams) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(QualifiedModel)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultTimeoutSeconds != nil {
		in, out := &in.DefaultTimeoutSeconds, &out.DefaultTimeoutSeconds
		*out = new(int)
		**out = **in
	}
	if in.DefaultMaxConcurrency != nil {
		in, out := &in.DefaultMaxConcurrency, &out.DefaultMaxConcurrency
		*out = new(int)
		**out = **in
	}
	if in.MaxDocumentTokens != nil {
		in, out := &in.MaxDocumentTokens, &out.MaxDocumentTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContextualRetrievalParams.
func (in *ContextualRetrievalParams) DeepCopy() *ContextualRetrievalParams {
	if in == nil {
		return nil
	}
	out := new(ContextualRetrievalParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProvider) DeepCopyInto(out *CustomProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make(map[string]SecretKeyRef, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProvider.
func (in *CustomProvider) DeepCopy() *CustomProvider {
	if in == nil {
		return nil
	}
	out := new(CustomProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionConfig) DeepCopyInto(out *DistributionConfig) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make([]ProviderInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AvailableDistributions != nil {
		in, out := &in.AvailableDistributions, &out.AvailableDistributions
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionConfig.
func (in *DistributionConfig) DeepCopy() *DistributionConfig {
	if in == nil {
		return nil
	}
	out := new(DistributionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributionSpec) DeepCopyInto(out *DistributionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributionSpec.
func (in *DistributionSpec) DeepCopy() *DistributionSpec {
	if in == nil {
		return nil
	}
	out := new(DistributionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DoclingServeProvider) DeepCopyInto(out *DoclingServeProvider) {
	*out = *in
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.DefaultChunkSizeTokens != nil {
		in, out := &in.DefaultChunkSizeTokens, &out.DefaultChunkSizeTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DoclingServeProvider.
func (in *DoclingServeProvider) DeepCopy() *DoclingServeProvider {
	if in == nil {
		return nil
	}
	out := new(DoclingServeProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAccessConfig) DeepCopyInto(out *ExternalAccessConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAccessConfig.
func (in *ExternalAccessConfig) DeepCopy() *ExternalAccessConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalAccessConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileBatchParams) DeepCopyInto(out *FileBatchParams) {
	*out = *in
	if in.MaxConcurrentFilesPerBatch != nil {
		in, out := &in.MaxConcurrentFilesPerBatch, &out.MaxConcurrentFilesPerBatch
		*out = new(int)
		**out = **in
	}
	if in.FileBatchChunkSize != nil {
		in, out := &in.FileBatchChunkSize, &out.FileBatchChunkSize
		*out = new(int)
		**out = **in
	}
	if in.CleanupIntervalSeconds != nil {
		in, out := &in.CleanupIntervalSeconds, &out.CleanupIntervalSeconds
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileBatchParams.
func (in *FileBatchParams) DeepCopy() *FileBatchParams {
	if in == nil {
		return nil
	}
	out := new(FileBatchParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileIngestionParams) DeepCopyInto(out *FileIngestionParams) {
	*out = *in
	if in.DefaultChunkSizeTokens != nil {
		in, out := &in.DefaultChunkSizeTokens, &out.DefaultChunkSizeTokens
		*out = new(int)
		**out = **in
	}
	if in.DefaultChunkOverlapTokens != nil {
		in, out := &in.DefaultChunkOverlapTokens, &out.DefaultChunkOverlapTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileIngestionParams.
func (in *FileIngestionParams) DeepCopy() *FileIngestionParams {
	if in == nil {
		return nil
	}
	out := new(FileIngestionParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileProcessorChunkConfig) DeepCopyInto(out *FileProcessorChunkConfig) {
	*out = *in
	if in.DefaultChunkSizeTokens != nil {
		in, out := &in.DefaultChunkSizeTokens, &out.DefaultChunkSizeTokens
		*out = new(int)
		**out = **in
	}
	if in.DefaultChunkOverlapTokens != nil {
		in, out := &in.DefaultChunkOverlapTokens, &out.DefaultChunkOverlapTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileProcessorChunkConfig.
func (in *FileProcessorChunkConfig) DeepCopy() *FileProcessorChunkConfig {
	if in == nil {
		return nil
	}
	out := new(FileProcessorChunkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileProcessorsInlineProviders) DeepCopyInto(out *FileProcessorsInlineProviders) {
	*out = *in
	if in.Auto != nil {
		in, out := &in.Auto, &out.Auto
		*out = new(InlineAutoFileProcessorProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.PyPDF != nil {
		in, out := &in.PyPDF, &out.PyPDF
		*out = new(InlinePyPDFFileProcessorProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.MarkItDown != nil {
		in, out := &in.MarkItDown, &out.MarkItDown
		*out = new(InlineMarkItDownFileProcessorProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Docling != nil {
		in, out := &in.Docling, &out.Docling
		*out = new(InlineDoclingFileProcessorProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileProcessorsInlineProviders.
func (in *FileProcessorsInlineProviders) DeepCopy() *FileProcessorsInlineProviders {
	if in == nil {
		return nil
	}
	out := new(FileProcessorsInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileProcessorsProvidersSpec) DeepCopyInto(out *FileProcessorsProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(FileProcessorsRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(FileProcessorsInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileProcessorsProvidersSpec.
func (in *FileProcessorsProvidersSpec) DeepCopy() *FileProcessorsProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(FileProcessorsProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileProcessorsRemoteProviders) DeepCopyInto(out *FileProcessorsRemoteProviders) {
	*out = *in
	if in.DoclingServe != nil {
		in, out := &in.DoclingServe, &out.DoclingServe
		*out = new(DoclingServeProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileProcessorsRemoteProviders.
func (in *FileProcessorsRemoteProviders) DeepCopy() *FileProcessorsRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(FileProcessorsRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSearchDisplayParams) DeepCopyInto(out *FileSearchDisplayParams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSearchDisplayParams.
func (in *FileSearchDisplayParams) DeepCopy() *FileSearchDisplayParams {
	if in == nil {
		return nil
	}
	out := new(FileSearchDisplayParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesInlineProviders) DeepCopyInto(out *FilesInlineProviders) {
	*out = *in
	if in.LocalFS != nil {
		in, out := &in.LocalFS, &out.LocalFS
		*out = new(InlineLocalFSProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesInlineProviders.
func (in *FilesInlineProviders) DeepCopy() *FilesInlineProviders {
	if in == nil {
		return nil
	}
	out := new(FilesInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesProvidersSpec) DeepCopyInto(out *FilesProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(FilesRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(FilesInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesProvidersSpec.
func (in *FilesProvidersSpec) DeepCopy() *FilesProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(FilesProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesRemoteProviders) DeepCopyInto(out *FilesRemoteProviders) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Provider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesRemoteProviders.
func (in *FilesRemoteProviders) DeepCopy() *FilesRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(FilesRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HNSWConfig) DeepCopyInto(out *HNSWConfig) {
	*out = *in
	if in.M != nil {
		in, out := &in.M, &out.M
		*out = new(int)
		**out = **in
	}
	if in.EfConstruction != nil {
		in, out := &in.EfConstruction, &out.EfConstruction
		*out = new(int)
		**out = **in
	}
	if in.EfSearch != nil {
		in, out := &in.EfSearch, &out.EfSearch
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HNSWConfig.
func (in *HNSWConfig) DeepCopy() *HNSWConfig {
	if in == nil {
		return nil
	}
	out := new(HNSWConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IVFFlatConfig) DeepCopyInto(out *IVFFlatConfig) {
	*out = *in
	if in.Nlist != nil {
		in, out := &in.Nlist, &out.Nlist
		*out = new(int)
		**out = **in
	}
	if in.Nprobe != nil {
		in, out := &in.Nprobe, &out.Nprobe
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IVFFlatConfig.
func (in *IVFFlatConfig) DeepCopy() *IVFFlatConfig {
	if in == nil {
		return nil
	}
	out := new(IVFFlatConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityConfig) DeepCopyInto(out *IdentityConfig) {
	*out = *in
	out.Cert = in.Cert
	out.Key = in.Key
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityConfig.
func (in *IdentityConfig) DeepCopy() *IdentityConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceInlineProviders) DeepCopyInto(out *InferenceInlineProviders) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceInlineProviders.
func (in *InferenceInlineProviders) DeepCopy() *InferenceInlineProviders {
	if in == nil {
		return nil
	}
	out := new(InferenceInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceProvidersSpec) DeepCopyInto(out *InferenceProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(InferenceRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(InferenceInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceProvidersSpec.
func (in *InferenceProvidersSpec) DeepCopy() *InferenceProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceRemoteProviders) DeepCopyInto(out *InferenceRemoteProviders) {
	*out = *in
	if in.VLLM != nil {
		in, out := &in.VLLM, &out.VLLM
		*out = make([]VLLMProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OpenAI != nil {
		in, out := &in.OpenAI, &out.OpenAI
		*out = make([]OpenAIProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = make([]AzureProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Bedrock != nil {
		in, out := &in.Bedrock, &out.Bedrock
		*out = make([]BedrockProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VertexAI != nil {
		in, out := &in.VertexAI, &out.VertexAI
		*out = make([]VertexAIProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Watsonx != nil {
		in, out := &in.Watsonx, &out.Watsonx
		*out = make([]WatsonxProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceRemoteProviders.
func (in *InferenceRemoteProviders) DeepCopy() *InferenceRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(InferenceRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineAutoFileProcessorProvider) DeepCopyInto(out *InlineAutoFileProcessorProvider) {
	*out = *in
	in.FileProcessorChunkConfig.DeepCopyInto(&out.FileProcessorChunkConfig)
	if in.ExtractMetadata != nil {
		in, out := &in.ExtractMetadata, &out.ExtractMetadata
		*out = new(bool)
		**out = **in
	}
	if in.CleanText != nil {
		in, out := &in.CleanText, &out.CleanText
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineAutoFileProcessorProvider.
func (in *InlineAutoFileProcessorProvider) DeepCopy() *InlineAutoFileProcessorProvider {
	if in == nil {
		return nil
	}
	out := new(InlineAutoFileProcessorProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineBuiltinResponsesProvider) DeepCopyInto(out *InlineBuiltinResponsesProvider) {
	*out = *in
	if in.VectorStoresConfig != nil {
		in, out := &in.VectorStoresConfig, &out.VectorStoresConfig
		*out = new(VectorStoresConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CompactionConfig != nil {
		in, out := &in.CompactionConfig, &out.CompactionConfig
		*out = new(CompactionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineBuiltinResponsesProvider.
func (in *InlineBuiltinResponsesProvider) DeepCopy() *InlineBuiltinResponsesProvider {
	if in == nil {
		return nil
	}
	out := new(InlineBuiltinResponsesProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineDoclingFileProcessorProvider) DeepCopyInto(out *InlineDoclingFileProcessorProvider) {
	*out = *in
	in.FileProcessorChunkConfig.DeepCopyInto(&out.FileProcessorChunkConfig)
	if in.DoOCR != nil {
		in, out := &in.DoOCR, &out.DoOCR
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineDoclingFileProcessorProvider.
func (in *InlineDoclingFileProcessorProvider) DeepCopy() *InlineDoclingFileProcessorProvider {
	if in == nil {
		return nil
	}
	out := new(InlineDoclingFileProcessorProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineFileSearchProvider) DeepCopyInto(out *InlineFileSearchProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	if in.VectorStoresConfig != nil {
		in, out := &in.VectorStoresConfig, &out.VectorStoresConfig
		*out = new(VectorStoresConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineFileSearchProvider.
func (in *InlineFileSearchProvider) DeepCopy() *InlineFileSearchProvider {
	if in == nil {
		return nil
	}
	out := new(InlineFileSearchProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineLocalFSProvider) DeepCopyInto(out *InlineLocalFSProvider) {
	*out = *in
	if in.TTLSecs != nil {
		in, out := &in.TTLSecs, &out.TTLSecs
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineLocalFSProvider.
func (in *InlineLocalFSProvider) DeepCopy() *InlineLocalFSProvider {
	if in == nil {
		return nil
	}
	out := new(InlineLocalFSProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineMarkItDownFileProcessorProvider) DeepCopyInto(out *InlineMarkItDownFileProcessorProvider) {
	*out = *in
	in.FileProcessorChunkConfig.DeepCopyInto(&out.FileProcessorChunkConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineMarkItDownFileProcessorProvider.
func (in *InlineMarkItDownFileProcessorProvider) DeepCopy() *InlineMarkItDownFileProcessorProvider {
	if in == nil {
		return nil
	}
	out := new(InlineMarkItDownFileProcessorProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlinePyPDFFileProcessorProvider) DeepCopyInto(out *InlinePyPDFFileProcessorProvider) {
	*out = *in
	in.FileProcessorChunkConfig.DeepCopyInto(&out.FileProcessorChunkConfig)
	if in.ExtractMetadata != nil {
		in, out := &in.ExtractMetadata, &out.ExtractMetadata
		*out = new(bool)
		**out = **in
	}
	if in.CleanText != nil {
		in, out := &in.CleanText, &out.CleanText
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlinePyPDFFileProcessorProvider.
func (in *InlinePyPDFFileProcessorProvider) DeepCopy() *InlinePyPDFFileProcessorProvider {
	if in == nil {
		return nil
	}
	out := new(InlinePyPDFFileProcessorProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InlineReferenceProvider) DeepCopyInto(out *InlineReferenceProvider) {
	*out = *in
	if in.MaxConcurrentBatches != nil {
		in, out := &in.MaxConcurrentBatches, &out.MaxConcurrentBatches
		*out = new(int)
		**out = **in
	}
	if in.MaxConcurrentRequestsPerBatch != nil {
		in, out := &in.MaxConcurrentRequestsPerBatch, &out.MaxConcurrentRequestsPerBatch
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InlineReferenceProvider.
func (in *InlineReferenceProvider) DeepCopy() *InlineReferenceProvider {
	if in == nil {
		return nil
	}
	out := new(InlineReferenceProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KVStorageSpec) DeepCopyInto(out *KVStorageSpec) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KVStorageSpec.
func (in *KVStorageSpec) DeepCopy() *KVStorageSpec {
	if in == nil {
		return nil
	}
	out := new(KVStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MilvusProvider) DeepCopyInto(out *MilvusProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MilvusProvider.
func (in *MilvusProvider) DeepCopy() *MilvusProvider {
	if in == nil {
		return nil
	}
	out := new(MilvusProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelConfig) DeepCopyInto(out *ModelConfig) {
	*out = *in
	if in.ContextLength != nil {
		in, out := &in.ContextLength, &out.ContextLength
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelConfig.
func (in *ModelConfig) DeepCopy() *ModelConfig {
	if in == nil {
		return nil
	}
	out := new(ModelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelContextProtocolProvider) DeepCopyInto(out *ModelContextProtocolProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelContextProtocolProvider.
func (in *ModelContextProtocolProvider) DeepCopy() *ModelContextProtocolProvider {
	if in == nil {
		return nil
	}
	out := new(ModelContextProtocolProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfig) DeepCopyInto(out *NetworkConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Proxy != nil {
		in, out := &in.Proxy, &out.Proxy
		*out = new(ProxyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(TimeoutConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfig.
func (in *NetworkConfig) DeepCopy() *NetworkConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PolicyTypes != nil {
		in, out := &in.PolicyTypes, &out.PolicyTypes
		*out = make([]v1.PolicyType, len(*in))
		copy(*out, *in)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]v1.NetworkPolicyIngressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]v1.NetworkPolicyEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkSpec) DeepCopyInto(out *NetworkSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
	if in.ExternalAccess != nil {
		in, out := &in.ExternalAccess, &out.ExternalAccess
		*out = new(ExternalAccessConfig)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkSpec.
func (in *NetworkSpec) DeepCopy() *NetworkSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXServer) DeepCopyInto(out *OGXServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXServer.
func (in *OGXServer) DeepCopy() *OGXServer {
	if in == nil {
		return nil
	}
	out := new(OGXServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OGXServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXServerList) DeepCopyInto(out *OGXServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OGXServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXServerList.
func (in *OGXServerList) DeepCopy() *OGXServerList {
	if in == nil {
		return nil
	}
	out := new(OGXServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OGXServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXServerSpec) DeepCopyInto(out *OGXServerSpec) {
	*out = *in
	out.Distribution = in.Distribution
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = new(ProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StateStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DisabledAPIs != nil {
		in, out := &in.DisabledAPIs, &out.DisabledAPIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RegistryRefreshIntervalSeconds != nil {
		in, out := &in.RegistryRefreshIntervalSeconds, &out.RegistryRefreshIntervalSeconds
		*out = new(int32)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BaseConfig != nil {
		in, out := &in.BaseConfig, &out.BaseConfig
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
	if in.OverrideConfig != nil {
		in, out := &in.OverrideConfig, &out.OverrideConfig
		*out = new(ConfigMapKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXServerSpec.
func (in *OGXServerSpec) DeepCopy() *OGXServerSpec {
	if in == nil {
		return nil
	}
	out := new(OGXServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXServerStatus) DeepCopyInto(out *OGXServerStatus) {
	*out = *in
	in.Version.DeepCopyInto(&out.Version)
	in.DistributionConfig.DeepCopyInto(&out.DistributionConfig)
	if in.ResolvedDistribution != nil {
		in, out := &in.ResolvedDistribution, &out.ResolvedDistribution
		*out = new(ResolvedDistributionStatus)
		**out = **in
	}
	if in.ConfigGeneration != nil {
		in, out := &in.ConfigGeneration, &out.ConfigGeneration
		*out = new(ConfigGenerationStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalURL != nil {
		in, out := &in.ExternalURL, &out.ExternalURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXServerStatus.
func (in *OGXServerStatus) DeepCopy() *OGXServerStatus {
	if in == nil {
		return nil
	}
	out := new(OGXServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OGXServerValidator) DeepCopyInto(out *OGXServerValidator) {
	*out = *in
	if in.KnownDistributionNames != nil {
		in, out := &in.KnownDistributionNames, &out.KnownDistributionNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OGXServerValidator.
func (in *OGXServerValidator) DeepCopy() *OGXServerValidator {
	if in == nil {
		return nil
	}
	out := new(OGXServerValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenAIProvider) DeepCopyInto(out *OpenAIProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
	out.APIKey = in.APIKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenAIProvider.
func (in *OpenAIProvider) DeepCopy() *OpenAIProvider {
	if in == nil {
		return nil
	}
	out := new(OpenAIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCStorageSpec) DeepCopyInto(out *PVCStorageSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCStorageSpec.
func (in *PVCStorageSpec) DeepCopy() *PVCStorageSpec {
	if in == nil {
		return nil
	}
	out := new(PVCStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgvectorProvider) DeepCopyInto(out *PgvectorProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	out.Password = in.Password
	if in.VectorIndex != nil {
		in, out := &in.VectorIndex, &out.VectorIndex
		*out = new(VectorIndexConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgvectorProvider.
func (in *PgvectorProvider) DeepCopy() *PgvectorProvider {
	if in == nil {
		return nil
	}
	out := new(PgvectorProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetSpec) DeepCopyInto(out *PodDisruptionBudgetSpec) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetSpec.
func (in *PodDisruptionBudgetSpec) DeepCopy() *PodDisruptionBudgetSpec {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderHealthStatus) DeepCopyInto(out *ProviderHealthStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderHealthStatus.
func (in *ProviderHealthStatus) DeepCopy() *ProviderHealthStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderHealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderInfo) DeepCopyInto(out *ProviderInfo) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	out.Health = in.Health
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderInfo.
func (in *ProviderInfo) DeepCopy() *ProviderInfo {
	if in == nil {
		return nil
	}
	out := new(ProviderInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvidersSpec) DeepCopyInto(out *ProvidersSpec) {
	*out = *in
	if in.Inference != nil {
		in, out := &in.Inference, &out.Inference
		*out = new(InferenceProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.VectorIo != nil {
		in, out := &in.VectorIo, &out.VectorIo
		*out = new(VectorIOProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ToolRuntime != nil {
		in, out := &in.ToolRuntime, &out.ToolRuntime
		*out = new(ToolRuntimeProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(FilesProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Batches != nil {
		in, out := &in.Batches, &out.Batches
		*out = new(BatchesProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = new(ResponsesProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FileProcessors != nil {
		in, out := &in.FileProcessors, &out.FileProcessors
		*out = new(FileProcessorsProvidersSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvidersSpec.
func (in *ProvidersSpec) DeepCopy() *ProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(ProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(string)
		**out = **in
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(string)
		**out = **in
	}
	if in.CACert != nil {
		in, out := &in.CACert, &out.CACert
		*out = new(string)
		**out = **in
	}
	if in.NoProxy != nil {
		in, out := &in.NoProxy, &out.NoProxy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QdrantProvider) DeepCopyInto(out *QdrantProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.APIKey != nil {
		in, out := &in.APIKey, &out.APIKey
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.GRPCPort != nil {
		in, out := &in.GRPCPort, &out.GRPCPort
		*out = new(int)
		**out = **in
	}
	if in.PreferGRPC != nil {
		in, out := &in.PreferGRPC, &out.PreferGRPC
		*out = new(bool)
		**out = **in
	}
	if in.HTTPS != nil {
		in, out := &in.HTTPS, &out.HTTPS
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QdrantProvider.
func (in *QdrantProvider) DeepCopy() *QdrantProvider {
	if in == nil {
		return nil
	}
	out := new(QdrantProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QualifiedModel) DeepCopyInto(out *QualifiedModel) {
	*out = *in
	if in.EmbeddingDimensions != nil {
		in, out := &in.EmbeddingDimensions, &out.EmbeddingDimensions
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QualifiedModel.
func (in *QualifiedModel) DeepCopy() *QualifiedModel {
	if in == nil {
		return nil
	}
	out := new(QualifiedModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteInferenceCommonConfig) DeepCopyInto(out *RemoteInferenceCommonConfig) {
	*out = *in
	if in.AllowedModels != nil {
		in, out := &in.AllowedModels, &out.AllowedModels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RefreshModels != nil {
		in, out := &in.RefreshModels, &out.RefreshModels
		*out = new(bool)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteInferenceCommonConfig.
func (in *RemoteInferenceCommonConfig) DeepCopy() *RemoteInferenceCommonConfig {
	if in == nil {
		return nil
	}
	out := new(RemoteInferenceCommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RerankerModel) DeepCopyInto(out *RerankerModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RerankerModel.
func (in *RerankerModel) DeepCopy() *RerankerModel {
	if in == nil {
		return nil
	}
	out := new(RerankerModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedDistributionStatus) DeepCopyInto(out *ResolvedDistributionStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedDistributionStatus.
func (in *ResolvedDistributionStatus) DeepCopy() *ResolvedDistributionStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedDistributionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesSpec) DeepCopyInto(out *ResourcesSpec) {
	*out = *in
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]ModelConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesSpec.
func (in *ResourcesSpec) DeepCopy() *ResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponsesInlineProviders) DeepCopyInto(out *ResponsesInlineProviders) {
	*out = *in
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = new(InlineBuiltinResponsesProvider)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponsesInlineProviders.
func (in *ResponsesInlineProviders) DeepCopy() *ResponsesInlineProviders {
	if in == nil {
		return nil
	}
	out := new(ResponsesInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponsesProvidersSpec) DeepCopyInto(out *ResponsesProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(ResponsesRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(ResponsesInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponsesProvidersSpec.
func (in *ResponsesProvidersSpec) DeepCopy() *ResponsesProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(ResponsesProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponsesRemoteProviders) DeepCopyInto(out *ResponsesRemoteProviders) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponsesRemoteProviders.
func (in *ResponsesRemoteProviders) DeepCopy() *ResponsesRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(ResponsesRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteQueryParams) DeepCopyInto(out *RewriteQueryParams) {
	*out = *in
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(QualifiedModel)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
	if in.Temperature != nil {
		in, out := &in.Temperature, &out.Temperature
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteQueryParams.
func (in *RewriteQueryParams) DeepCopy() *RewriteQueryParams {
	if in == nil {
		return nil
	}
	out := new(RewriteQueryParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedProviderBase) DeepCopyInto(out *RoutedProviderBase) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedProviderBase.
func (in *RoutedProviderBase) DeepCopy() *RoutedProviderBase {
	if in == nil {
		return nil
	}
	out := new(RoutedProviderBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Provider) DeepCopyInto(out *S3Provider) {
	*out = *in
	if in.AWSAccessKeyID != nil {
		in, out := &in.AWSAccessKeyID, &out.AWSAccessKeyID
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AWSSecretAccessKey != nil {
		in, out := &in.AWSSecretAccessKey, &out.AWSSecretAccessKey
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AutoCreateBucket != nil {
		in, out := &in.AutoCreateBucket, &out.AutoCreateBucket
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Provider.
func (in *S3Provider) DeepCopy() *S3Provider {
	if in == nil {
		return nil
	}
	out := new(S3Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLStorageSpec) DeepCopyInto(out *SQLStorageSpec) {
	*out = *in
	if in.ConnectionString != nil {
		in, out := &in.ConnectionString, &out.ConnectionString
		*out = new(SecretKeyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLStorageSpec.
func (in *SQLStorageSpec) DeepCopy() *SQLStorageSpec {
	if in == nil {
		return nil
	}
	out := new(SQLStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StateStorageSpec) DeepCopyInto(out *StateStorageSpec) {
	*out = *in
	if in.KV != nil {
		in, out := &in.KV, &out.KV
		*out = new(KVStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQL != nil {
		in, out := &in.SQL, &out.SQL
		*out = new(SQLStorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StateStorageSpec.
func (in *StateStorageSpec) DeepCopy() *StateStorageSpec {
	if in == nil {
		return nil
	}
	out := new(StateStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSClientConfig) DeepCopyInto(out *TLSClientConfig) {
	*out = *in
	if in.Trust != nil {
		in, out := &in.Trust, &out.Trust
		*out = new(TrustConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSClientConfig.
func (in *TLSClientConfig) DeepCopy() *TLSClientConfig {
	if in == nil {
		return nil
	}
	out := new(TLSClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(bool)
		**out = **in
	}
	if in.Ciphers != nil {
		in, out := &in.Ciphers, &out.Ciphers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TavilySearchProvider) DeepCopyInto(out *TavilySearchProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	out.APIKey = in.APIKey
	if in.MaxResults != nil {
		in, out := &in.MaxResults, &out.MaxResults
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TavilySearchProvider.
func (in *TavilySearchProvider) DeepCopy() *TavilySearchProvider {
	if in == nil {
		return nil
	}
	out := new(TavilySearchProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutConfig) DeepCopyInto(out *TimeoutConfig) {
	*out = *in
	if in.Connect != nil {
		in, out := &in.Connect, &out.Connect
		*out = new(int)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutConfig.
func (in *TimeoutConfig) DeepCopy() *TimeoutConfig {
	if in == nil {
		return nil
	}
	out := new(TimeoutConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRuntimeInlineProviders) DeepCopyInto(out *ToolRuntimeInlineProviders) {
	*out = *in
	if in.FileSearch != nil {
		in, out := &in.FileSearch, &out.FileSearch
		*out = make([]InlineFileSearchProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRuntimeInlineProviders.
func (in *ToolRuntimeInlineProviders) DeepCopy() *ToolRuntimeInlineProviders {
	if in == nil {
		return nil
	}
	out := new(ToolRuntimeInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRuntimeProvidersSpec) DeepCopyInto(out *ToolRuntimeProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(ToolRuntimeRemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(ToolRuntimeInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRuntimeProvidersSpec.
func (in *ToolRuntimeProvidersSpec) DeepCopy() *ToolRuntimeProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(ToolRuntimeProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolRuntimeRemoteProviders) DeepCopyInto(out *ToolRuntimeRemoteProviders) {
	*out = *in
	if in.BraveSearch != nil {
		in, out := &in.BraveSearch, &out.BraveSearch
		*out = make([]BraveSearchProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TavilySearch != nil {
		in, out := &in.TavilySearch, &out.TavilySearch
		*out = make([]TavilySearchProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModelContextProtocol != nil {
		in, out := &in.ModelContextProtocol, &out.ModelContextProtocol
		*out = make([]ModelContextProtocolProvider, len(*in))
		copy(*out, *in)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolRuntimeRemoteProviders.
func (in *ToolRuntimeRemoteProviders) DeepCopy() *ToolRuntimeRemoteProviders {
	if in == nil {
		return nil
	}
	out := new(ToolRuntimeRemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustConfig) DeepCopyInto(out *TrustConfig) {
	*out = *in
	if in.CACertificates != nil {
		in, out := &in.CACertificates, &out.CACertificates
		*out = make([]ConfigMapKeyRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustConfig.
func (in *TrustConfig) DeepCopy() *TrustConfig {
	if in == nil {
		return nil
	}
	out := new(TrustConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VLLMProvider) DeepCopyInto(out *VLLMProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
	if in.APIToken != nil {
		in, out := &in.APIToken, &out.APIToken
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.MaxTokens != nil {
		in, out := &in.MaxTokens, &out.MaxTokens
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VLLMProvider.
func (in *VLLMProvider) DeepCopy() *VLLMProvider {
	if in == nil {
		return nil
	}
	out := new(VLLMProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorIOInlineProviders) DeepCopyInto(out *VectorIOInlineProviders) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorIOInlineProviders.
func (in *VectorIOInlineProviders) DeepCopy() *VectorIOInlineProviders {
	if in == nil {
		return nil
	}
	out := new(VectorIOInlineProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorIOProvidersSpec) DeepCopyInto(out *VectorIOProvidersSpec) {
	*out = *in
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(VectorIORemoteProviders)
		(*in).DeepCopyInto(*out)
	}
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(VectorIOInlineProviders)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorIOProvidersSpec.
func (in *VectorIOProvidersSpec) DeepCopy() *VectorIOProvidersSpec {
	if in == nil {
		return nil
	}
	out := new(VectorIOProvidersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorIORemoteProviders) DeepCopyInto(out *VectorIORemoteProviders) {
	*out = *in
	if in.Pgvector != nil {
		in, out := &in.Pgvector, &out.Pgvector
		*out = make([]PgvectorProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Milvus != nil {
		in, out := &in.Milvus, &out.Milvus
		*out = make([]MilvusProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Qdrant != nil {
		in, out := &in.Qdrant, &out.Qdrant
		*out = make([]QdrantProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]CustomProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorIORemoteProviders.
func (in *VectorIORemoteProviders) DeepCopy() *VectorIORemoteProviders {
	if in == nil {
		return nil
	}
	out := new(VectorIORemoteProviders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorIndexConfig) DeepCopyInto(out *VectorIndexConfig) {
	*out = *in
	if in.HNSW != nil {
		in, out := &in.HNSW, &out.HNSW
		*out = new(HNSWConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IVFFlat != nil {
		in, out := &in.IVFFlat, &out.IVFFlat
		*out = new(IVFFlatConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorIndexConfig.
func (in *VectorIndexConfig) DeepCopy() *VectorIndexConfig {
	if in == nil {
		return nil
	}
	out := new(VectorIndexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VectorStoresConfig) DeepCopyInto(out *VectorStoresConfig) {
	*out = *in
	if in.DefaultEmbeddingModel != nil {
		in, out := &in.DefaultEmbeddingModel, &out.DefaultEmbeddingModel
		*out = new(QualifiedModel)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultRerankerModel != nil {
		in, out := &in.DefaultRerankerModel, &out.DefaultRerankerModel
		*out = new(RerankerModel)
		**out = **in
	}
	if in.RewriteQueryParams != nil {
		in, out := &in.RewriteQueryParams, &out.RewriteQueryParams
		*out = new(RewriteQueryParams)
		(*in).DeepCopyInto(*out)
	}
	if in.FileSearchParams != nil {
		in, out := &in.FileSearchParams, &out.FileSearchParams
		*out = new(FileSearchDisplayParams)
		**out = **in
	}
	if in.ContextPromptParams != nil {
		in, out := &in.ContextPromptParams, &out.ContextPromptParams
		*out = new(ContextPromptParams)
		**out = **in
	}
	if in.AnnotationPromptParams != nil {
		in, out := &in.AnnotationPromptParams, &out.AnnotationPromptParams
		*out = new(AnnotationPromptParams)
		(*in).DeepCopyInto(*out)
	}
	if in.FileIngestionParams != nil {
		in, out := &in.FileIngestionParams, &out.FileIngestionParams
		*out = new(FileIngestionParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ChunkRetrievalParams != nil {
		in, out := &in.ChunkRetrievalParams, &out.ChunkRetrievalParams
		*out = new(ChunkRetrievalParams)
		(*in).DeepCopyInto(*out)
	}
	if in.FileBatchParams != nil {
		in, out := &in.FileBatchParams, &out.FileBatchParams
		*out = new(FileBatchParams)
		(*in).DeepCopyInto(*out)
	}
	if in.ContextualRetrievalParams != nil {
		in, out := &in.ContextualRetrievalParams, &out.ContextualRetrievalParams
		*out = new(ContextualRetrievalParams)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VectorStoresConfig.
func (in *VectorStoresConfig) DeepCopy() *VectorStoresConfig {
	if in == nil {
		return nil
	}
	out := new(VectorStoresConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionInfo) DeepCopyInto(out *VersionInfo) {
	*out = *in
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionInfo.
func (in *VersionInfo) DeepCopy() *VersionInfo {
	if in == nil {
		return nil
	}
	out := new(VersionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VertexAIProvider) DeepCopyInto(out *VertexAIProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VertexAIProvider.
func (in *VertexAIProvider) DeepCopy() *VertexAIProvider {
	if in == nil {
		return nil
	}
	out := new(VertexAIProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatsonxProvider) DeepCopyInto(out *WatsonxProvider) {
	*out = *in
	out.RoutedProviderBase = in.RoutedProviderBase
	in.RemoteInferenceCommonConfig.DeepCopyInto(&out.RemoteInferenceCommonConfig)
	out.APIKey = in.APIKey
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatsonxProvider.
func (in *WatsonxProvider) DeepCopy() *WatsonxProvider {
	if in == nil {
		return nil
	}
	out := new(WatsonxProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadOverrides) DeepCopyInto(out *WorkloadOverrides) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadOverrides.
func (in *WorkloadOverrides) DeepCopy() *WorkloadOverrides {
	if in == nil {
		return nil
	}
	out := new(WorkloadOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadSpec) DeepCopyInto(out *WorkloadSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(PVCStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(PodDisruptionBudgetSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = new(WorkloadOverrides)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadSpec.
func (in *WorkloadSpec) DeepCopy() *WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}
